/**
 * Share landing (en) — ShareLandingView
 * Note: title/poster/posterHide/savePoster/sharePoster/tips/meals/brand are existing keys, must be kept.
 */
export default {
  title: 'Trip Share',
  poster: 'Generate Poster',
  posterHide: 'Hide Poster',
  savePoster: 'Save Poster',
  sharePoster: 'Share Poster',
  tips: 'Tips',
  meals: 'Meals',
  brand: '—— Generated by AI Travel Assistant ——',
  invalidLink: 'Invalid share link',
  notFound: 'Share content not found',
  linkExpired: 'The link may have expired',
  fallbackTitle: 'Trip',
  peopleTravel: '{n} people traveling together',
  dayN: 'Day {n}',
}
